### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by stlim0730** [stlim0730/glide#36]
GLIDE currently doesn't support HTTPS connection.

**Comment by radames** [comment]
maybe choose a random domain name to start and use https://letsencrypt.org/?

**Comment by radames** [comment]
@stlim0730 could make this a priority? I'm not sure about oauth exchange with github in a now https environment is a good idea to start

**Comment by stlim0730** [comment]
Alright. I'm working on it.

**Comment by stlim0730** [comment]
Done. I'll close this issue after some tests.

**Comment by radames** [comment]
perfect! thanks
