### ISSUE TITLE
Possibility of hide components on Code & Test

### ISSUE THREAD

**Issue by radames** [stlim0730/glide#59]
In order to have more space on the screen while coding and previewing, would be nice to be able to hide the Files Panel and maybe Status panel. With keyboard shortcuts or panel hide icon.

**Comment by radames** [comment]
this would be great, because the students could have more space for the text editor 
also dragging and resizing the panels?

<img width="1680" alt="panel" src="https://user-images.githubusercontent.com/102277/39728536-66d3c5e4-520c-11e8-96d1-de2a0d122189.png">

**Comment by stlim0730** [comment]
The code editor now supports expand & compress.
